name: Decompile SRS

on:
  workflow_dispatch:

jobs:
  decompile:
    runs-on: ubuntu-latest

    env:
      SINGBOX_VERSION: "1.12.0"

    steps:
      - name: Download sing-box
        run: |
          wget -q \
            https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz \
            -O sing-box.tar.gz

          tar -xzf sing-box.tar.gz

          chmod +x sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box

      - name: Download geoip-ru.srs
        run: |
          wget -q \
            https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-ru.srs \
            -O geoip-ru.srs

      - name: Decompile
        run: |
          ./sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box \
            rule-set decompile \
            --output geoip-ru.json \
            geoip-ru.srs

      - name: Upload JSON
        uses: actions/upload-artifact@v4
        with:
          name: geoip-ru-json
          path: geoip-ru.json
