- name: Download geoip-ru.srs
  run: |
    wget -q \
      https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-ru.srs \
      -O geoip-ru.srs

- name: Decompile
  run: |
    tools/sing-box \
      rule-set decompile \
      -o geoip-ru.json \
      geoip-ru.srs
