name: Update GEOIP_RU

on:
  workflow_dispatch:

  schedule:
    - cron: "15 3 * * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SINGBOX_VERSION: "1.12.0"

    steps:

      - uses: actions/checkout@v4

      - name: Download sing-box
        run: |
          wget -q \
            https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz \
            -O sing-box.tar.gz

          tar -xzf sing-box.tar.gz

          chmod +x sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box

      - name: Download geoip-ru.srs
        run: |
          wget -q \
            https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-ru.srs \
            -O geoip-ru.srs

      - name: Decompile
        run: |
          ./sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box \
            rule-set decompile \
            --output geoip-ru.json \
            geoip-ru.srs

      - name: Generate RouterOS script
        run: |

          mkdir -p output

          {
            echo "/ip firewall address-list"
            echo
            echo "remove [find list=\"GEOIP_RU\" comment=\"GEOIP_RU_Auto\"]"
            echo

            jq -r '
              .rules[0].ip_cidr[]
              | select(test(":") | not)
              | "add list=GEOIP_RU address=\(.) comment=\"GEOIP_RU_Auto\""
            ' geoip-ru.json

          } > output/geoip-ru.rsc
          
      - name: Check generated file
        run: |

          COUNT=$(grep -c '^add ' output/geoip-ru.rsc)

          echo "IPv4 prefixes: $COUNT"

          if [ "$COUNT" -lt 10000 ]; then
            echo "Too few prefixes!"
            exit 1
          fi

      - name: Commit changes
        run: |

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output/geoip-ru.rsc

          if git diff --cached --quiet
          then
            echo "Nothing changed."
          else
            git commit -m "Update GEOIP_RU"
            git push
          fi
